name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex

      - name: commit doc
        run: |
          git config --local user.email "test@github.com"
          git config --local user.name  "GitHub Action [bot]"
          git add -f "*.pdf"
          git commit -m "auto-update PDF files"

